// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7YibJkKPdcGDtNL6c-QxHuvfFOYhINc',
    appId: '1:496768958985:android:574057967846c4d8dbaed8',
    messagingSenderId: '496768958985',
    projectId: 'aftaler-og-regnskab',
    storageBucket: 'aftaler-og-regnskab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Wz-lTu1zBeon40ORz1W2NMGiEnRB9Ew',
    appId: '1:496768958985:ios:6aeeeb76924f845cdbaed8',
    messagingSenderId: '496768958985',
    projectId: 'aftaler-og-regnskab',
    storageBucket: 'aftaler-og-regnskab.firebasestorage.app',
    iosBundleId: 'com.jakobjacobsen.aftalerOgRegnskab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfsXKi9Cx9JkOd6jpZUG1eRolsn16XBo0',
    appId: '1:496768958985:web:8e6b6efae30a1988dbaed8',
    messagingSenderId: '496768958985',
    projectId: 'aftaler-og-regnskab',
    authDomain: 'aftaler-og-regnskab.firebaseapp.com',
    storageBucket: 'aftaler-og-regnskab.firebasestorage.app',
    measurementId: 'G-0VGLWCL65K',
  );
}
